version: '3'

services:
    redis:
        image: redis/redis-stack:latest
        container_name: redis.coding-challenge.docker
        restart: unless-stopped
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        ports:
            - 127.0.0.1:${REDIS_PORT}:6379
        networks:
            - global
networks:
    global:
        external: true